id: P009527
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD152296
  title: ཚད་མའི་རིགས་ལམ་བྱིས་པའི་གར་སྟེགས།
  author: ''
  volumes:
    8adfca07d966494f8ed25007e7000493:
      image_group_id: I2PD19662
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
