id: P009527
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:36:31.627581
source_metadata:
  id: bdr:W1PD152296
  title: ཚད་མའི་རིགས་ལམ་བྱིས་པའི་གར་སྟེགས།
  author: ''
  volumes:
    8adfca07d966494f8ed25007e7000493:
      image_group_id: I2PD19662
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
